# Generated by Django 6.0.2 on 2026-02-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_wishlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
