# Generated by Django 6.0.2 on 2026-02-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
